"""
Sakhi — Chat Image Generation Service (Rate-Limited)
======================================================
Provides daily-quota-gated image generation for use inside the chat flow.

Quota: each child profile may generate up to CHAT_IMAGE_DAILY_LIMIT images
per UTC calendar day (default: 3, configurable via env var).

Usage:
    from services.chat_image_service import generate_chat_image, QuotaExceededError

    try:
        result = await generate_chat_image(
            profile_id="...",
            prompt="a red hot air balloon over a green valley",
        )
        # result == {"image_url": "https://...", "remaining_today": 2}
    except QuotaExceededError:
        # return HTTP 429 to the caller
"""

import logging
import os
import uuid
from datetime import datetime, timezone

from db.pool import get_pool
from services.image_generation import ImageGenerationService

logger = logging.getLogger("sakhi.chat_image")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Default daily image limit per child profile.
# Override by setting CHAT_IMAGE_DAILY_LIMIT in the environment.
_DEFAULT_DAILY_LIMIT = 100


def _get_daily_limit() -> int:
    try:
        return int(os.getenv("CHAT_IMAGE_DAILY_LIMIT", str(_DEFAULT_DAILY_LIMIT)))
    except (ValueError, TypeError):
        return _DEFAULT_DAILY_LIMIT


# ---------------------------------------------------------------------------
# Custom exception
# ---------------------------------------------------------------------------


class QuotaExceededError(Exception):
    """Raised when a profile has exhausted its daily image generation quota."""


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


async def get_daily_usage(profile_id: str) -> int:
    """Return the number of images generated by this profile today (UTC)."""
    pool = get_pool()
    today_start = datetime.now(timezone.utc).replace(
        hour=0, minute=0, second=0, microsecond=0
    )
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            """
            SELECT COUNT(*) AS cnt
            FROM chat_image_usage
            WHERE profile_id = $1
              AND created_at >= $2
            """,
            uuid.UUID(profile_id),
            today_start,
        )
    return int(row["cnt"]) if row else 0


async def _record_usage(profile_id: str) -> None:
    """Insert one usage row for the profile (called after successful generation)."""
    pool = get_pool()
    async with pool.acquire() as conn:
        await conn.execute(
            """
            INSERT INTO chat_image_usage (profile_id)
            VALUES ($1)
            """,
            uuid.UUID(profile_id),
        )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

_image_service: ImageGenerationService | None = None


def _get_image_service() -> ImageGenerationService:
    global _image_service
    if _image_service is None:
        _image_service = ImageGenerationService()
    return _image_service


async def generate_chat_image(
    profile_id: str,
    prompt: str,
    aspect_ratio: str = "1:1",
) -> dict:
    """
    Generate one image for a chat message, subject to the daily quota.

    Args:
        profile_id: UUID string of the child's profile.
        prompt:     User-supplied description of the image to draw.
        aspect_ratio: Target aspect ratio — "1:1" (default), "16:9", or "4:3".

    Returns:
        {"image_url": str, "remaining_today": int}

    Raises:
        QuotaExceededError: if the profile has hit its daily limit.
        ValueError:         if the prompt is empty.
        RuntimeError:       if the Replicate API call fails.
    """
    if not prompt or not prompt.strip():
        raise ValueError("Image prompt cannot be empty")

    daily_limit = _get_daily_limit()
    used = await get_daily_usage(profile_id)

    if used >= daily_limit:
        logger.info(
            f"Chat image quota exhausted for profile {profile_id}: "
            f"{used}/{daily_limit} used today"
        )
        raise QuotaExceededError(
            f"Daily image limit of {daily_limit} reached for this profile"
        )

    logger.info(
        f"Generating chat image for profile {profile_id}: "
        f"'{prompt[:60]}' [{aspect_ratio}] — usage {used + 1}/{daily_limit}"
    )

    service = _get_image_service()
    image_url = await service.generate_image(
        prompt=prompt.strip(),
        aspect_ratio=aspect_ratio,
        output_format="webp",
        num_outputs=1,
    )

    if not image_url:
        raise RuntimeError("Image generation failed — Replicate returned no URL")

    await _record_usage(profile_id)

    remaining = daily_limit - (used + 1)
    logger.info(
        f"Chat image generated for profile {profile_id}. "
        f"Remaining today: {remaining}"
    )

    return {
        "image_url": image_url,
        "remaining_today": remaining,
    }
